[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.mypy]
mypy_path = "backend" # mypyの実行起点となるディレクトリを指定

# 厳格な型チェックの設定
no_implicit_optional = true
python_version = "3.12"

# インポート解決のための設定
explicit_package_bases = true
namespace_packages = true
